import Image from 'next/image';
import Head from 'next/head';

import { MdKeyboardArrowDown, MdOutlineGroup, MdAccountCircle, MdLogout } from 'react-icons/md';

import * as S from '../styles/dashboard';
import pfpPlaceholder from '../assets/Profile_avatar_placeholder_large.png';
import logo from '../assets/devchallenges.svg';
import Button from '../components/Button';
import { useState } from 'react';

const Dashboard = () => {
  const [options, setOptions] = useState(false);


  return (
    <S.Container>

      <Head>
        <title>Authentication App - Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.HeaderContainer>
        <Image src={logo} width={120} height={18} alt='logo' />

        <S.HeaderInfo onClick={() => setOptions(prev => !prev)} isOpen={options}>
          <Image src={pfpPlaceholder} width={32} height={32} alt='profile image'/>
          <span>Xanthe Neal</span>
          <MdKeyboardArrowDown />
          {
            options && (

              <S.OptionContainer>
                <S.Option isActive={true}>
                  <MdAccountCircle size={20} color={'#4F4F4F'}/>
                  <span>My Profile</span>
                </S.Option>

                <S.Option isActive={false}>
                  <MdOutlineGroup size={20} color={'#4F4F4F'}/>
                  <span>Group Chat</span>
                </S.Option>

                <hr />

                <S.Option isActive={false}>
                  <MdLogout size={20} color={'#EB5757'}/>
                  <span style={{color: '#EB5757'}}>Logout</span>
                </S.Option>
              </S.OptionContainer>
            )
          }
        </S.HeaderInfo>
      </S.HeaderContainer>

      <S.ContentContainer>
        <h2>Personal Info</h2>
        <span>Basic info, like your name and photo</span>

        <S.Content>
          <S.ContentSection isHeader={true}>
            <div>
              <h2>Profile</h2>
              <p>Some info may be visible to other people</p>
            </div>

            <Button isEdit={true}>Edit</Button>
          </S.ContentSection>

          <S.ContentSection>
            <S.Title>PHOTO</S.Title>
            <Image src={pfpPlaceholder} width={72} height={72} alt='profile image'/>
          </S.ContentSection>
          <S.ContentSection>
            <S.Title>NAME</S.Title>
            <p>Xanthe Neal</p>
          </S.ContentSection>
          <S.ContentSection>
            <S.Title>BIO</S.Title>
            <p>I am a software developer and a big fan of devchallenges...</p>
          </S.ContentSection>
          <S.ContentSection>
            <S.Title>PHONE</S.Title>
            <p>908249274292</p>
          </S.ContentSection>
          <S.ContentSection>
            <S.Title>EMAIL</S.Title>
            <p>xanthe.neal@gmail.com</p>
          </S.ContentSection>
          <S.ContentSection>
            <S.Title>PASSWORD</S.Title>
            <p>************</p>
          </S.ContentSection>
        </S.Content>
      </S.ContentContainer>
    </S.Container>
  );
};

export default Dashboard;
